### ISSUE TITLE
Question concerning an implementation of HueVis.

### ISSUE THREAD

**Issue by chincheta0815** [daniel1111/HueLibEnt#4]
Hi daniel1111,

I found your great project and remembered that I once had the same issue on coupling squeezelite with hue.
So I worked on LMS-to-Hue (https://github.com/chincheta0815/LMS-to-Hue/tree/master/helper/LMS-to-Hue)

That thing discovers the Bridge, shows it as a LMS player, gets the music stream and is supposed to analyze it and flash the lights.

So far the idea. Until now that thing simply has issues with the correct stream output:
1. I do not know if I get 16bit PCM correctly and the if I split up the channels correctly.
2. Since point 1 I do not know if the analysis is correct.

But maybe you like the project. If you have any hints on how to get the audio stream and the analysis correctly I would also be happy.

BTW: I had to add minor functions to libHueEnt as I needed the apiversion. Maybe some headers (and functions) should be named more "liebhueent" specific (debug.h --> hue_debug.h, dtls.h --> hue_dtls.h) or so...
Do you want me to send as a pull request?

Best regards

**Comment by daniel1111** [comment]
Hi chincheta0815,

LMS-to-Hue sounds awesome, I'm going to have to give that a go soon :)
Unfortunately I can't really help with the stream output :( I pretty much ripped off the the audio capture and analysis code from the CAVA project, to avoid having to deal with that as far as possible (bit of a cop out, I know).

And yes, a PR to add a function to get the api version and/or rename the headers to hue_* would certainly be appreciated :)
TBH naming the headers isn't something I'd really thought about, but that naming scheme makes sense

**Comment by chincheta0815** [comment]
Okay, then I will do some cleanup (in both things) and send you a PR concerning the headers. In a later point it might also make sense to split up some file due to organization...

 Concerning the Hue Bridge I think I got the correct samples for the channels, but there is somewhere a bug... I think it is related to buffer size framerate etc. First point: not all lights flash and/or they do not flash (values too high)
